name: p3bind
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - scipy
  - tqdm
  - biopython
  - jupyter
  - pip:
      - torch
